root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp/server"
  cmd = "go build -ldflags='-s -w' -o tmp/server ./cmd/server/main.go"
  delay = 2000 # ms
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "tests"]
  exclude_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true
  exclude_unchanged = false
  follow_symlink = false

[log]
  time = true

[color]
  main = "cyan"
  watcher = "yellow"
  building = "magenta"
  runner = "green"
  app = "blue"
  error = "red"
